### ISSUE TITLE
Some SDXL Images lead to crash

### ISSUE THREAD

**Issue by tkoenig89** [tkoenig89/ComfyUI_Load_Image_With_Metadata#2]
![image](https://github.com/tkoenig89/ComfyUI_Load_Image_With_Metadata/assets/1177652/9f7dbd5f-52d9-426a-8ab9-97afe7d4b0a4)

**Comment by tkoenig89** [comment]
seems to be a general issue with complex graphs

**Comment by green-anger** [comment]
With [this ComfyUI commit](https://github.com/comfyanonymous/ComfyUI/commit/30eb92c3cbe0e0dfa442d452b5f1187c654e572e) it gives the same error for the simplest flow, the node itself and its positive and negative outputs linked to two text nodes.

**Comment by tkoenig89** [comment]
i just pushed an update i fetched from the image-data-reader package this node is based on. This update should support SDXL and some other SD generators. maybe this fixes your issue.

Sadly there are still a lot of cases when reading comfy workflows, when it crashes parsing the data.

**Comment by green-anger** [comment]
@tkoenig89 It doesn't crush now, but at the same time it doesn't extract data. The simplest demo workflow is at the end of this comment (cannot attach json, so put it as code). It uses custom nodes ttN textDebug and Text Multiline from WAS (can be easily installed with [the manager](https://github.com/ltdrdata/ComfyUI-Manager)). The only purpose for using the two is convenience of testing. The multiline input gets to the debug text node, while the two text output from the Meta node do not.

I think the idea behind this node is great and I can see using it in a separate upscale workflow, it can save a lot of time. I'm not proficient in Python at all, so it's difficult for me to see why it doesn't extract data. As I understand PNG did not always supported Exif, there were PNG chunks. Is there any way to see how Comfy saves the data. It's possible to see all the metadata with [ImageMagick](https://imagemagick.org/), but how is it saved? Quick search led me to [PyPNG](https://pypng.readthedocs.io/en/latest/chunk.html) that can read chunks, it was last updated in 2022 while piexif in 2019.

What do you think about [Pillow](https://pypi.org/project/Pillow/), can it do the job? It's being actively supported and seems powerful.

<details>
  <summary>Workflow content</summary>

```json
{
  "last_node_id": 15,
  "last_link_id": 15,
  "nodes": [
    {
      "id": 11,
      "type": "ttN textDebug",
      "pos": [
        650,
        540
      ],
      "size": [
        450,
        190
      ],
      "flags": {},
      "order": 2,
      "mode": 0,
      "inputs": [
        {
          "name": "text",
          "type": "STRING",
          "link": 14
        }
      ],
      "outputs": [
        {
          "name": "text",
          "type": "STRING",
          "links": null,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "ttN textDebug"
      },
      "widgets_values": [
        true,
        ""
      ]
    },
    {
      "id": 10,
      "type": "LoadImageWithMetadata",
      "pos": [
        90,
        570
      ],
      "size": [
        315,
        454
      ],
      "flags": {},
      "order": 0,
      "mode": 0,
      "outputs": [
        {
          "name": "image",
          "type": "IMAGE",
          "links": null,
          "shape": 3
        },
        {
          "name": "mask",
          "type": "MASK",
          "links": null,
          "shape": 3
        },
        {
          "name": "positive",
          "type": "STRING",
          "links": [
            14
          ],
          "shape": 3,
          "slot_index": 2
        },
        {
          "name": "negative",
          "type": "STRING",
          "links": [
            11
          ],
          "shape": 3,
          "slot_index": 3
        },
        {
          "name": "seed",
          "type": "INT",
          "links": null,
          "shape": 3
        },
        {
          "name": "width",
          "type": "INT",
          "links": null,
          "shape": 3
        },
        {
          "name": "height",
          "type": "INT",
          "links": null,
          "shape": 3
        },
        {
          "name": "cfg",
          "type": "FLOAT",
          "links": null,
          "shape": 3
        },
        {
          "name": "steps",
          "type": "INT",
          "links": null,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "LoadImageWithMetadata"
      },
      "widgets_values": [
        "ComfyUI_00075_.png",
        "image"
      ]
    },
    {
      "id": 12,
      "type": "ttN textDebug",
      "pos": [
        650,
        800
      ],
      "size": [
        433.3728970614345,
        185.30092551491475
      ],
      "flags": {},
      "order": 3,
      "mode": 0,
      "inputs": [
        {
          "name": "text",
          "type": "STRING",
          "link": 11
        }
      ],
      "outputs": [
        {
          "name": "text",
          "type": "STRING",
          "links": null,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "ttN textDebug"
      },
      "widgets_values": [
        true,
        ""
      ]
    },
    {
      "id": 15,
      "type": "Text Multiline",
      "pos": [
        70,
        1100
      ],
      "size": {
        "0": 400,
        "1": 200
      },
      "flags": {},
      "order": 1,
      "mode": 0,
      "outputs": [
        {
          "name": "STRING",
          "type": "STRING",
          "links": [
            15
          ],
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "Text Multiline"
      },
      "widgets_values": [
        "Testing"
      ]
    },
    {
      "id": 14,
      "type": "ttN textDebug",
      "pos": [
        660,
        1100
      ],
      "size": {
        "0": 433.3728942871094,
        "1": 185.30091857910156
      },
      "flags": {},
      "order": 4,
      "mode": 0,
      "inputs": [
        {
          "name": "text",
          "type": "STRING",
          "link": 15,
          "slot_index": 0
        }
      ],
      "outputs": [
        {
          "name": "text",
          "type": "STRING",
          "links": null,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "ttN textDebug",
        "ttNnodeVersion": "1.0.0"
      },
      "widgets_values": [
        true,
        "Testing"
      ]
    }
  ],
  "links": [
    [
      11,
      10,
      3,
      12,
      0,
      "STRING"
    ],
    [
      14,
      10,
      2,
      11,
      0,
      "STRING"
    ],
    [
      15,
      15,
      0,
      14,
      0,
      "STRING"
    ]
  ],
  "groups": [],
  "config": {},
  "extra": {},
  "version": 0.4
}
```
</details>

**Comment by tkoenig89** [comment]
@green-anger the big issue with comfy is, it does not save metadata at all. It just stores the graph of your workflow. The tool my node is based on just tries to reversly go through this node and figure out what the prompt, seed etc. might be. But as soon as there is a node it does not know or some operation on the prompt (concat, split ...) happens, it fails to handle this case. 

So the underlying issue here is not, how to retrieve the data from the png or jpg, but how to make sense of this data. 

The best bet at the moment i found so far ist, to have a separate node in your initial worklfow, that saves the metadata plain (like A1111) into the image. Then there should be now issue, when using my node to retrieve this metadata.

**Comment by green-anger** [comment]
@tkoenig89 Thank you for the explanation, I see what you mean now. I manually read the data, there're two significant parts, prompt and workflow. The latter hold all the info about nodes on the canvas, it has no data about the content. The prompt part does have it but instead of injecting values it has "links" (basically numbers) to the incoming nodes which in turn can have other incoming nodes. I have this situation in one of my flows with switches, it's saved as deeply nested nodes in the meta.

In this case I think it's not worth investing into "reverse engineering", at least until Comfy has a separate section for the prompt. Unfortunately, that may never happen since Comfy allows to have any node combination and the same flow can have multiple text encoders, you'll never know which one is the true source.

May I ask what you meant in your last para? Do you mean putting the prompt as text into the text encoder instead of linking another node to it? How can we let your node know from where to pull the prompt info?

**Comment by tkoenig89** [comment]
Sure, sorry that part was really a little confusing i guess :D. So let me take some more lines explaining what i think might be a solution:

So it is all about getting around the issue, that you don't have any usable metadata by default. So before we tried to only catch the issue when its too late and you only have the workflow at hand. So what you might want to do, is update the workflow that is generating your images. There is a node you use as a replacement for the "save image" node, just like you might replace the "load image" node with mine. 

There are a few out there, but this one you can find via comfy manager: https://github.com/giriss/comfy-image-saver. 
I did not do a lot of digging there, but basically you manually plug in your data into this node. It will then store everything in the format that a1111 uses. So metadata is directly accessible inside the image file.

The files saved with this metadata can easily be read by my node, as the tool it is based on supports a lot of formats for the metadata. 

The caveat of this solution is, that it only works with images you create from the moment you update your generating workflow.  And of course, you have to add a lot of connections to an already existing workflow, to save prompt, seed and so on.

**Comment by green-anger** [comment]
@tkoenig89 Thanks a bunch for the link, I didn't see this node before!

Reworking workflows is not a problem, it can be fun on its own.

I'll give the combo a try, it sounds promising. Thanks again! 👍

**Comment by green-anger** [comment]
@tkoenig89 I've tried it and it gives this error now:

![load-meta-error](https://github.com/tkoenig89/ComfyUI_Load_Image_With_Metadata/assets/7919497/20fdd1dd-fd9e-43fa-85c3-943c8253bcd5)

comfy-image-saver @ [65e6903](https://github.com/giriss/comfy-image-saver/commit/65e6903eff274a50f8b5cd768f0f96baf37baea1)
this node @ 6e60238

**Comment by tkoenig89** [comment]
Looked at it, and it's in issue with the Node. It saves not 100% compatible with A1111 format. I opened an issue here:
https://github.com/giriss/comfy-image-saver/issues/10

**Comment by tkoenig89** [comment]
@green-anger If you don't care about cfg scale i have pushed a fix. My node will now ignore paramters it cannot parse from metadata. This way you can still use other values like positive, negative prompt.

**Comment by green-anger** [comment]
@tkoenig89 Yes, it works now! 🎉 Thanks a lot!

CFG is not that useful to be honest. For an upscaling flow the most important are the prompts and (probably) seed, image size is very convenient, but steps and cfg are so-so. Would be great to get sampler and scheduler, but I'm not sure if it's usually saved in meta data.

**Comment by tkoenig89** [comment]
Closing, as the bug is fixed. 

Tracking model and sampler as separate feature request: https://github.com/tkoenig89/ComfyUI_Load_Image_With_Metadata/issues/5
