### ISSUE TITLE
Feature request: save image with metadata

### ISSUE THREAD

**Issue by paulhoux** [tkoenig89/ComfyUI_Load_Image_With_Metadata#4]
Hi, thanks for making this ComfyUi addon. 

As you mentioned yourself, ComfyUi's metadata is quite a mess. I wasn't able to reconstruct the prompt and settings from an image I made earlier. It seems reconstructing the complete workflow is the only option.

With that being said: would it be possible to add a node to this addon which saves an image with metadata in the selected format? That way, I can first use ComfyUi to reconstruct the image workflow, then add the SaveImageWithMetadata node and select the metadata format. I then have an image I should be able to load using LoadImageWithMetadata.

My goal eventually is to have a folder containing images with just the following metadata:
 * positive prompt
 * negative prompt
 * checkpoint name

This will be enough for me to run an upscaler script for each of the image files in the folder.

**Comment by tkoenig89** [comment]
Sounds reasonable to have this step added to the initial workflow, as you might have a clear view of what goes into the prompts and we don't need to reconstruct this later by going through the node tree.

I saw this a few days back on reddit, maybe this is already what you need:
https://www.reddit.com/r/comfyui/comments/15pz7ak/node_to_save_image_and_option_to_save_text_prompt/
https://www.reddit.com/r/comfyui/comments/15tjz0b/biggest_let_down_of_comfyui_you_loose_generation/

The later seems to be more 'professional' but i did not have a close look at any of these. This one seems to save in A1111 format which should automatically work with my node.

**Comment by tkoenig89** [comment]
Github link: https://github.com/giriss/comfy-image-saver

Seems to have a minor compatibility issue at the moment. This causes CFG scale to not be readable by my node.

**Comment by tkoenig89** [comment]
For anyone looking for a all in one solution (save and load nodes) made by the original author of the prompt reader, please use this node collection here:

https://github.com/receyuki/comfyui-prompt-reader-node

I guess this one can be loaded via comfy manager as well.
